"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const controllers_1 = require("../controllers");
const express = require('express');
const routeRole = express.Router();
routeRole.get('/get-list-role', controllers_1.RoleController.GetList);
routeRole.post('/create-role', controllers_1.RoleController.CreateRole);
routeRole.put('/update-role', controllers_1.RoleController.UpdateRole);
routeRole.delete('/delete-role/:id', controllers_1.RoleController.DeleteRole);
routeRole.delete('/delete-roles', controllers_1.RoleController.DeleteMultipleRoles);
exports.default = routeRole;
